### ISSUE TITLE
Warnings raise when dealing with geometries that have duplicate points

### ISSUE THREAD

**Issue by Lukasz-Piekarek** [shapely/shapely#1552] opened 2022-09-27 11:02 UTC
## Expected behavior and actual behavior.

I see warnings being raised when working with a LineString that has the first point duplicated.
Shapely 1.8.4 does not complain in the same cases.

## Steps to reproduce the problem.

```
from shapely.geometry import Point, LineString
Point(2, 2).distance(LineString([(0, 0), (1, 1)]))
... 1.4142135623730951
... Point(2, 2).distance(LineString([(0, 0), (1, 1), (1, 1)]))
... 1.4142135623730951
... Point(2, 2).distance(LineString([(0, 0), (0, 0), (1, 1)]))
/opt/venv39/lib/python3.9/site-packages/shapely/measurement.py:74: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
```

## Operating system

Ubuntu 20.04

## Shapely version and provenance

Shapely 2.0a1 installed using pip
pip install shapely==2.0a1
I am comparing behavior with 1.8.4

**Comment by jorisvandenbossche** [comment] 2022-09-27 12:24
We have seen similar issues before, see for example https://github.com/pygeos/pygeos/issues/404, https://github.com/pygeos/pygeos/issues/167 (and for example https://github.com/shapely/shapely/issues/1345 for a different operation). 
The "overflow" warnings should be fixed on the GEOS side, but the "invalid value" warning apparently not (https://github.com/pygeos/pygeos/issues/404 mentions both those warnings, and also mentions that the "invalid value" warning goes away by making the geometry valid / normalizing)

Specifically the "invalid value" warning in this case of repeated points (with a nice reproducer) could maybe be reported to upstream GEOS. Although there is also already this issue that (unsuccessfully) tried to find the cause of some of those warnings: https://github.com/libgeos/geos/issues/515

**Closed** 2023-01-23 20:33 UTC
Labels: shapely 2.0
