### ISSUE TITLE
Shapely operations return geometries with incorrect winding

### ISSUE THREAD

**Issue by adam-sikora** [shapely/shapely#1766] opened 2023-02-20 11:06 UTC
Geometry operations like `intersection`, `union`, `difference`... produce incorrectly (clockwise) winded objects. Even if input geometries were CCW winded.

## Expected behavior and actual behavior.

The operations should produce geometries with correct CCW winding.

## Steps to reproduce the problem.

```
b = box(0, 0, 1, 1)

print(b.exterior.is_ccw)
print(b.intersection(b).exterior.is_ccw)
print(b.union(b).exterior.is_ccw)
print(b.difference(b).exterior.is_ccw)
```

## Shapely version

shapely==2.0.1

**Comment by brendan-ward** [comment] 2023-02-20 17:21
"incorrect" is a matter of opinion / implementation...

This is expected behavior from GEOS, which is the C/C++ library used by Shapely.  My understanding is that the implementation of winding order for exterior / interior rings in GEOS / JTS (the companion Java library on which it is based) predates winding order being established in the OGC Simple Features standard (counter clockwise for exterior rings, clockwise for interiors).

For inputs, GEOS doesn't care about winding order because exterior and interior rings are specified directly; in other implementations winding order is used to determine which ring is exterior vs interior.  For outputs, except for rare functions where Shapely has more direct control over the coordinate order, they have clockwise exterior rings.

For `box` specifically, you can specify the [ccw](https://shapely.readthedocs.io/en/stable/reference/shapely.box.html#shapely.box); however, most functions do not provide direct control over winding order.

Elsewhere you can use `is_cw` / `is_ccw` / `reverse` and in the future probably [force_ccw](https://github.com/shapely/shapely/pull/1690) to check and manipulate winding order.

Since this issue is about winding order, which is technically correct given the underlying geometry engine, and not a bug in Shapely, I'm going to close this.

**Closed by brendan-ward** 2023-02-20 17:21 UTC

**Comment by jorisvandenbossche** [comment] 2023-02-20 20:56
I have been meaning to open an issue on the GEOS side about that it would be nice to provide some way to tweak this default orientation for newly created geometries (not necessarily a trivial change though)
