### ISSUE TITLE
Wrong intersection with polygons intersecting on a line

### ISSUE THREAD

**Issue by marcomgg** [shapely/shapely#1427] opened 2022-06-20 14:57 UTC
## Expected behavior and actual behavior.
The intersection of these two polygons should be a segment
```
poly_a = Polygon(
    [
        [4.330127018922193, 2.5000000000000004],
        [6.830127018922194, -1.830127018922194],
        [4.2320508075688785, -3.330127018922194],
        [1.7320508075688772, 1.0],
        [4.330127018922193, 2.5000000000000004],
    ]
)
poly_b = Polygon(
    [
        [4.330127018922193, 2.5000000000000004],
        [5.830127018922193, -0.09807621135331557],
        [7.562177826491071, 0.9019237886466849],
        [6.06217782649107, 3.500000000000001],
        [4.330127018922193, 2.5000000000000004],
    ]
)
```

but the resulting intersection is a polygon that is almost equal to poly_a

The two polygons are like this:
![polygons](https://user-images.githubusercontent.com/12584227/174580751-38a23796-baa7-438a-8dd9-b687b2ef9bb7.png)

## Operating system

Mac OS X 12.2.1, Apple M1 chip

## Shapely version and provenance
1.8.2 installed using PyPI

**Comment by jorisvandenbossche** [comment] 2022-08-15 07:33
@marcomgg thanks for the report!

This seems to be a bug in the underlying GEOS library. If you have installed using a wheel from PyPI, then normally GEOS 3.10.2 is included. I can reproduce this with that GEOS version:

```
In [3]: poly_a.intersection(poly_b).wkt
Out[3]: 'POLYGON ((5.830127018922193 -0.0980762113533154, 6.830127018922194 -1.830127018922194, 4.2320508075688785 -3.330127018922194, 1.7320508075688772 1, 4.330127018922193 2.5000000000000004, 5.830127018922193 -0.0980762113533154))'

In [5]: shapely.geos.geos_version
Out[5]: (3, 10, 2)
```

Using a more recent GEOS bug fix release 3.10.3 fixes this:

```
In [4]: poly_a.intersection(poly_b).wkt
Out[4]: 'LINESTRING (4.330127018922193 2.5000000000000004, 5.830127018922193 -0.0980762113533156)'

In [5]: shapely.geos.geos_version
Out[5]: (3, 10, 3)
```

Upgrading the GEOS version is not that straightforward when installing Shapely from PyPI (you would need to install GEOS separately, and then install shapely from source). Another option is to install from conda-forge (which already has a more recent GEOS). And the upcoming 1.8.3 release will actually include GEOS 3.10.3, so this might also solve it in the coming weeks (https://github.com/shapely/shapely/issues/1472, https://github.com/shapely/shapely/pull/1413)

**Comment by marcomgg** [comment] 2022-08-15 13:00
@jorisvandenbossche Thank you! Will wait for the 1.8.3 version then

**Comment by sgillies** [comment] 2022-08-16 15:56
@jorisvandenbossche thank you! There's no code fix for this, so I will close manually, and note in the change log.

**Closed by sgillies** 2022-08-16 15:56 UTC
Labels: geos, upstream bug, shapely-1.8
