### ISSUE TITLE
Valid/Invalid Polygon example in docs not working

### ISSUE THREAD

**Issue by connorferster** [shapely/shapely#1279] opened 2022-01-03 04:27 UTC
## Expected behavior and actual behavior.

The examples of valid and invalid polygons shown [here](https://shapely.readthedocs.io/en/stable/manual.html#polygons) both create valid polygons. Expected that polygons that share more than one point or share an edge would create an invalid polygon.

We found this problem working on [section-properties](https://github.com/robbievanleeuwen/section-properties/tree/v2) which is being overhauled to have shapely run it's new front-end (we love shapely!!!).

## Steps to reproduce the problem.

To recreate the example in the docs:

```python
exter = [(0, 0), (0, 2), (2, 2), (2, 0), (0, 0)]
inter = [(1, 0), (0, 1), (0.5, 1.5), (1.5, 0.5), (1, 0)]
(Polygon(exter) - Polygon(inter)) # Creates valid MultiPolygon even though two points in common
```

Produces this...

![image](https://user-images.githubusercontent.com/38441489/147905453-d0ebc775-b272-460a-b38d-51327183b830.png)

Instead of this...

![image](https://user-images.githubusercontent.com/38441489/147905525-a2f5431c-1f69-47be-8a62-2c9aac3da9f1.png)

## Operating system
Windows 10

## Shapely version and provenance
Shapely 1.80, installed from conda-forge using conda

**Comment by jorisvandenbossche** [comment] 2022-01-03 08:46
There is one difference with the example in the docs, though: having a Polygon vs MultiPolygon.

The example in the docs is created with (you can see it if you click on the "source code" link above the image):

```python
ext = [(0, 0), (0, 2), (2, 2), (2, 0), (0, 0)]
int = [(1, 0), (0, 1), (0.5, 1.5), (1.5, 0.5), (1, 0)][::-1]
polygon = Polygon(ext, [int])
```

This creates a single Polygon with a hole. And this is then indeed invalid:

```python
>>> polygon
<shapely.geometry.Polygon POLYGON ((0 0, 0 2, 2 2, 2 0, 0 0), (1 0, 1.5 0.5, 0.5 1.5, 0 1, 1 0))>
>>> polygon.is_valid
False
```

Your example, however, due to the slightly different way of creating the geometry (using the `difference` operation), gives a MultiPolygon:

```python
>>> multipolygon = Polygon(ext) - Polygon(int)  # Polygon(ext).difference(Polygon(int))
>>> multipolygon
<shapely.geometry.MultiPolygon MULTIPOLYGON (((0 1, 1 0, 0 0, 0 1)), ((0 2, 2 2, 2 0, 1 0, 1.5 0.5, 0.5 1.5, 0 1, 0 2)))>
>>> multipolygon.is_valid
True
```

I am no expert on the exact validity rules, but I _suppose_ that for MultiPolygon it is OK to touch at multiple points (while touching along a line or overlapping would result in invalid MultiPolygons)

**Comment by connorferster** [comment] 2022-01-03 16:39
Hi @jorisvandenbossche, I appreciate this point. This seems to create ambiguity, i.e. when is a Polygon with a hole a MultiPolygon and when is it a Polygon with a hole?

**Comment by jorisvandenbossche** [comment] 2022-01-03 18:11
If you visualize both, it can indeed be ambiguous (it might not be directly clear if it's a Polygon with a hole or a MultiPolygon). But code-wise there is no ambiguity when it is which: both objects in the example above have a different geometry type, and are represented by a different python class:

```python
>>> polygon.geom_type
'Polygon'
>>> type(polygon)
shapely.geometry.polygon.Polygon

>>>multipolygon.geom_type
'MultiPolygon'
>>> type(multipolygon)
shapely.geometry.multipolygon.MultiPolygon
```

**Comment by jorisvandenbossche** [comment] 2022-12-03 17:54
Given the above explanation, closing this as expected behaviour.

**Closed by jorisvandenbossche** 2022-12-03 17:54 UTC
