### ISSUE TITLE
Python 3.10 macOS x86_64 wheels missing on PyPI

### ISSUE THREAD

**Issue by adamjstewart** [shapely/shapely#1362] opened 2022-04-05 02:54 UTC
## Expected behavior and actual behavior.

There are Python 3.10 wheels available on PyPI for every platform other than macOS x86_64. There are macOS x86_64 wheels for all other versions of Python, so I'm guessing this was left out by accident.

## Steps to reproduce the problem.

Run `pip install shapely` on macOS x86_64 for Python 3.10 and see that it tries to build from source instead of using a wheel. Or just check https://pypi.org/project/Shapely/#files

## Operating system

macOS 10.15.7

## Shapely version and provenance

1.8.1.post1 installed from PyPI using pip

**Comment by mwtoews** [comment] 2022-04-05 11:05
Duplicate of #1348

**Closed by mwtoews** 2022-04-05 11:05 UTC
