### ISSUE TITLE
Attribute Error in Colab 

### ISSUE THREAD

**Issue by SanjuSoni** [shapely/shapely#1200] opened 2021-10-12 17:33 UTC
'Polygon' object has no attribute '_geom'

kindly comment me to solve this issue on Google Colab.

Also, the same code is working perfectly fine on my PC 

Detailed error is given below:

```


<ipython-input-3-adf2ecae91cd> in train_data(n, n2, nf)
     84     in_sqr = []
     85     for i in XY_f:
---> 86         if (Point(i).within(triangle) == 1):
     87             in_pt1.append(i)
     88 

/usr/local/lib/python3.7/dist-packages/shapely/geometry/base.py in within(self, other)
    777     def within(self, other):
    778         """Returns True if geometry is within the other, else False"""
--> 779         return bool(self.impl['within'](self, other))
    780 
    781     def equals_exact(self, other, tolerance):

/usr/local/lib/python3.7/dist-packages/shapely/predicates.py in __call__(self, this, other, *args)
     11     def __call__(self, this, other, *args):
     12         self._validate(this)
---> 13         self._validate(other, stop_prepared=True)
     14         try:
     15             return self.fn(this._geom, other._geom, *args)

/usr/local/lib/python3.7/dist-packages/shapely/topology.py in _validate(self, ob, stop_prepared)
     15 
     16     def _validate(self, ob, stop_prepared=False):
---> 17         if ob is None or ob._geom is None:
     18             raise ValueError("Null geometry supports no operations")
     19         if stop_prepared and hasattr(ob, 'prepared'):

AttributeError: 'Polygon' object has no attribute '_geom'

```

**Comment by sgillies** [comment] 2021-10-12 19:19
I can't reproduce it. Must be particular to your triangle.

![Screenshot from 2021-10-12 13-18-38](https://user-images.githubusercontent.com/33697/137016013-22890f6c-0ff9-47e9-a545-42ce02e7bf7e.png)

**Comment by sgillies** [comment] 2022-05-02 23:30
Closing. Shapely 1.7.x isn't supported any more.

**Closed by sgillies** 2022-05-02 23:30 UTC
