### ISSUE TITLE
Add parameter keep_collapsed to make_valid

### ISSUE THREAD

**Issue by theroggy** [shapely/shapely#1926] opened 2023-10-29 09:45 UTC
It would be practical to have the option to drop collapsed elements from geometries when `make_valid` is used.

With `keep_collapsed=True`, the current behaviour, e.g. after using `make_valid` on a MultiPolygon you can get a GeometryCollection as result (Eg. a LineString + a Polygon). If `keep_collapsed=False` non-polygon geometries would be removed from the result.

This behaviour is supported by `geos` using [GEOSMakeValidWithParams](https://libgeos.org/doxygen/geos__c_8h.html#ad378f6774219e39a87f46f4d2fa3e770)

Script with an example of the current behaviour:
```
import shapely

poly = shapely.from_wkt("MultiPolygon (((57479 202281, 57479 202259, 57454 202260, 57453 202277, 57479 202281),(57471 202270, 57471 202270, 57467 202270, 57471 202270)))")
print(f"poly.is_valid: {poly.is_valid}")
poly_valid = shapely.make_valid(poly)
print(f"poly_valid.is_valid: {poly_valid.is_valid}")
print(f"poly_valid: {poly_valid.wkt}")
```
Output:
```
poly.is_valid: False
poly_valid.is_valid: True
poly_valid: GEOMETRYCOLLECTION (POLYGON ((57479 202259, 57454 202260, 57453 202277, 57479 202281, 57479 202259)), LINESTRING (57471 202270, 57467 202270)) 
```

**Comment by jorisvandenbossche** [comment] 2023-11-26 15:46
Yes, that is certainly something we would like to add (and contributions welcome ;)) 
Going to close this as duplicate of https://github.com/shapely/shapely/issues/1415

**Closed by jorisvandenbossche** 2023-11-26 15:46 UTC
