### ISSUE TITLE
Add new Homebrew path for M1 to alt_paths for libgeos_c

### ISSUE THREAD

**Issue by YoungiiJC** [shapely/shapely#1080] opened 2021-02-01 07:07 UTC
## Expected behavior and actual behavior.
Shapley should look for `libgeos_c` in the new Homebrew path for M1 machines.

Here's the [release notes](https://brew.sh/2020/12/01/homebrew-2.6.0/) for Homebrew's path change on Apple silicon.

```
# shapely/geos.py

alt_paths = [
    # The Framework build from Kyng Chaos
    "/Library/Frameworks/GEOS.framework/Versions/Current/GEOS",
    # macports
    "/opt/local/lib/libgeos_c.dylib",
    # homebrew
    "/usr/local/lib/libgeos_c.dylib",
    # homebrew apple silicon M1 <-- add this
    "/opt/homebrew/lib/libgeos_c.dylib", <-- add this
]
```

I'm happy to open a PR on this ~

## Steps to reproduce the problem.
1. poetry install shapely
2. if on an M1 machine: run any script with shapely import

## Operating system
Mac OS X 11.1

## Shapely version and provenance
shapely 1.7.1, installed via poetry

**Comment by johnnync13** [comment] 2021-02-08 19:13
@YoungiiJC How I can fix this on docker like CVAT?
<img width="789" alt="Screenshot 2021-02-08 at 20 13 34" src="https://user-images.githubusercontent.com/22727137/107269600-207b2e80-6a4a-11eb-8d43-d3c33b4d143a.png">

**Comment by YoungiiJC** [comment] 2021-02-09 06:40
@johnnync13 I'm not familiar with Docker. What I did to fix this locally is edit the source code. This isn't an issue for me when I push to render.com, since they run on Linux. Sorry I can't be more helpful here :/

**Comment by sgillies** [comment] 2021-02-12 17:10
@johnnync13 your issue is not related. I don't think it's a Shapely issue at all, except in that you haven't satisfied the system requirements for building Shapely from a source distribution.

**Comment by sgillies** [comment] 2021-02-12 17:16
@YoungiiJC does the https://files.pythonhosted.org/packages/ff/62/69cca822e9ecf3f5eebae2105bccc04ed1818508df4f2b93f8464492f155/Shapely-1.7.1-cp39-cp39-macosx_10_9_x86_64.whl distribution not work at all for M1? My understanding is that the new macs come with some compatibility layer.

Also, will setting DYLD_LIBRARY_PATH not work? This was a good solution for me in the past when I was a mac user.

I'm reluctant to add a second alt path for homebrew since all of this dynamic loading of libgeos is going away in shapely 2.0.

**Comment by tino** [comment] 2021-02-14 16:50
I can confirm that setting `export DYLD_LIBRARY_PATH=/opt/homebrew/opt/geos/lib/` did the trick for me (on Apple Silicon), after having installed `brew install geos`.

**Comment by johnnync13** [comment] 2021-02-15 18:29
did you do with rosetta 2 terminal?

**Comment by YoungiiJC** [comment] 2021-02-17 10:08
hey @sgillies, sorry for the slow reply here. Yes, the new Macs have a compatibility layer called Rosetta 2. A lot of packages aren't ready for M1 yet, so we're stuck running them there. The consequence is that some things are installed for M1, others for Intel. It's a frustrating mess.

Shapely _should_ work just fine downloaded and run via a Rosetta 2 terminal instance, though I haven't tested it myself. In the case that I wind up doing an install of Shapely via Rosetta 2, I'm happy to report back here on it.

As for running Shapely on the M1 architecture, I did try setting the `DYLD_LIBRARY_PATH` in an M1 terminal instance, but it didn't work. I could've botched that. Instead I edited the source code per my recommendation above and things are running fine for me now. cc @johnnync13

**Comment by C4ptainCrunch** [comment] 2021-02-22 21:59
I can confirm that adding another alt_path like this works on M1:

```python
alt_paths = [
                # The Framework build from Kyng Chaos
                "/Library/Frameworks/GEOS.framework/Versions/Current/GEOS",
                # macports
                '/opt/local/lib/libgeos_c.dylib',
                # homebrew
                '/usr/local/lib/libgeos_c.dylib',
                # homebrew ARM
                '/opt/homebrew/lib/libgeos_c.dylib',
            ]
```

This is due to the fact that homebrew on ARM (not emulated through rosetta) is installed in `/opt/homebrew/` and not `/usr/local` as on x86 ([source](https://docs.brew.sh/FAQ#why-should-i-install-homebrew-in-the-default-location))

(As is did not install the x86 version of homebrew (nor python) `/usr/local` is empty on my machine)

**Comment by vincentsarago** [comment] 2021-03-02 20:38
just adding more to this, I'm also getting 

```
E   OSError: Could not find lib geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib', '/usr/local/lib/libgeos_c.dylib'].
``` 

but not on install. This error is happening when I do `from shapely.geos import lgeos`

I installed shapely using `pip install shapely --no-binary shapely` with GEOS installed on a custom path (I had `GEOS_CONFIG=/opt/bin/geos-config` set)

To me it's weird that this error happens on import ... if the library was installed without issue

to make things work on my side I had to add 
```python
    elif os.environ.get("GEOS_CONFIG"):
        geos_config = os.environ.get("GEOS_CONFIG")
        prefix, _ = subprocess.Popen([geos_config, "--prefix"], stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
        _lgeos = CDLL(os.path.join(prefix.decode('ascii').strip(), 'lib', 'libgeos_c.dylib'))
```
here: https://github.com/Toblerity/Shapely/blob/master/shapely/geos.py#L125

**Comment by sgillies** [comment] 2021-03-30 22:50
For 1.8, I'm considering adding an environment variable for adding paths to alt_paths. What do you think about that @vincentsarago ? GEOS_CONFIG isn't meant to be used at runtime. @jorisvandenbossche @mwtoews any objections to an environment variable for 1.8?

**Comment by mwtoews** [comment] 2021-03-31 00:35
@sgillies seems fine, and hopefully won't cause any surprises as `GEOS_CONFIG` is normally undefined for the majority of users. Would this be just for macOS? If it's for linux too, then it would obviously look for `libgeos_c.so`.

**Comment by griffindore** [comment] 2021-04-13 18:37
There appears to be a bad assumption about conda env usage too, and the `alt_paths` never get used as a fallback. When using a conda env, it can't find the path to my homebrew install.
```
~/miniconda3/envs/a-conda-env/lib/python3.7/site-packages/shapely/geos.py in <module>
    110     elif os.getenv('CONDA_PREFIX', ''):
    111         # conda package.
--> 112         _lgeos = CDLL(os.path.join(sys.prefix, 'lib', 'libgeos_c.dylib'))
```
which gives me this error:
```
OSError: dlopen(/Users/griffindore/miniconda3/envs/a-conda-env/lib/libgeos_c.dylib, 6): image not found
```

I use conda for envs but typically not for package installs. In this case I'm using homebrew GEOS and installed shapely via `pip install shapely --no-binary shapely` so that I can get it to be compatible with my pygeos install.

**Comment by jorisvandenbossche** [comment] 2021-04-13 18:52
>  so that I can get it to be compatible with my pygeos install.

@griffindore if you want to install both shapely and pygeos in a compatible way (using the same GEOS, for best performance), and if you are already using conda, I would highly recommend to install all of shapely, pygeos and geos from conda-forge, then you are sure they are compiled with / use the same GEOS library.

> There appears to be a bad assumption about conda env usage too

We might want to add an additional check that the file actually exists in the conda env, similarly as was recently done for windows (https://github.com/Toblerity/Shapely/pull/1108)

**Comment by agrawal-rohit** [comment] 2021-04-16 18:46
> just adding more to this, I'm also getting
> 
> ```
> E   OSError: Could not find lib geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib', '/usr/local/lib/libgeos_c.dylib'].
> ```
> 
> but not on install. This error is happening when I do `from shapely.geos import lgeos`
> 
> I installed shapely using `pip install shapely --no-binary shapely` with GEOS installed on a custom path (I had `GEOS_CONFIG=/opt/bin/geos-config` set)
> 
> To me it's weird that this error happens on import ... if the library was installed without issue
> 
> to make things work on my side I had to add
> 
> ```python
>     elif os.environ.get("GEOS_CONFIG"):
>         geos_config = os.environ.get("GEOS_CONFIG")
>         prefix, _ = subprocess.Popen([geos_config, "--prefix"], stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
>         _lgeos = CDLL(os.path.join(prefix.decode('ascii').strip(), 'lib', 'libgeos_c.dylib'))
> ```
> 
> here: https://github.com/Toblerity/Shapely/blob/master/shapely/geos.py#L125

I'm getting the same issue. Did you figure out a solution for this?

**Comment by griffindore** [comment] 2021-04-19 02:39
> > so that I can get it to be compatible with my pygeos install.
> 
> @griffindore if you want to install both shapely and pygeos in a compatible way (using the same GEOS, for best performance), and if you are already using conda, I would highly recommend to install all of shapely, pygeos and geos from conda-forge, then you are sure they are compiled with / use the same GEOS library.

Thanks, but I'm not already and certainly don't want to use conda for packages. It's just easier to install and configure miniconda on a machine than virtualenvwrapper, and I like it more for envs. In the off-chance that I really need a binary install of a package (e.g. pyqt), it's there at the ready. But the last thing I need is conda changing the versions of every other python package I use or taking a ton of time to resolve dependencies in my build/test machines. I'm more likely to go the other way and use a venv to workaround this!

**Comment by alukach** [comment] 2021-04-26 19:44
For my Apple M1 system with GDAL & GEOS installed via Hombrew, the following did the trick:

```
sudo ln -s /opt/homebrew/lib/libgeos_c.dylib /usr/local/lib
```

**Comment by femiir** [comment] 2021-05-20 17:07
> I can confirm that setting `export DYLD_LIBRARY_PATH=/opt/homebrew/opt/geos/lib/` did the trick for me (on Apple Silicon), after having installed `brew install geos`.

this work like magic 👌👌👌🧑🏾‍💻🧑🏾‍💻🧑🏾‍💻 code on

**Comment by camerondavison** [comment] 2021-06-08 20:18
is there any downside to adding the new homebrew location?

**Comment by mayteio** [comment] 2021-08-13 01:32
+1 for adding the new homebrew location, it's in PR: https://github.com/Toblerity/Shapely/pull/1176

**Comment by mayteio** [comment] 2021-08-13 01:42
If you're using venv, you'll need something like this in the meantime;

```
sudo ln -s /opt/homebrew/lib/libgeos_c.dylib venv/lib/libgeos_c.dylib
```

**Comment by iandees** [comment] 2021-12-04 04:48
This helps get rid of the "OSError: Could not find lib geos_c or load any of its variants" error:

```
ln -s /opt/homebrew/lib/libgeos_c.dylib venv/lib/libgeos_c.dylib
```

But now I get:

```
OSError: Could not find lib c or load any of its variants [].
```

(Sorry if this is straying from the original issue too much. I didn't see any obvious solutions. I've been spoiled by your wheels, Sean!)

**Comment by johnthagen** [comment] 2022-01-24 12:00
Is the fundamental issue here that there are no pre-compiled wheels uploaded to PyPI that support macOS ARM?

**Comment by knkumar** [comment] 2022-01-28 05:11
> This helps get rid of the "OSError: Could not find lib geos_c or load any of its variants" error:
> 
> ```
> ln -s /opt/homebrew/lib/libgeos_c.dylib venv/lib/libgeos_c.dylib
> ```
> 
> But now I get:
> 
> ```
> OSError: Could not find lib c or load any of its variants [].
> ```
> 
> (Sorry if this is straying from the original issue too much. I didn't see any obvious solutions. I've been spoiled by your wheels, Sean!)

Did you get this resolved?

**Comment by iandees** [comment] 2022-01-28 15:26
> Did you get this resolved?

No. In fact, I tried it again last night and ran into the same problem.

**Comment by llllvvuu** [comment] 2022-01-28 19:07
> This helps get rid of the "OSError: Could not find lib geos_c or load any of its variants" error:
> 
> ```
> ln -s /opt/homebrew/lib/libgeos_c.dylib venv/lib/libgeos_c.dylib
> ```
> 
> But now I get:
> 
> ```
> OSError: Could not find lib c or load any of its variants [].
> ```
> 
> (Sorry if this is straying from the original issue too much. I didn't see any obvious solutions. I've been spoiled by your wheels, Sean!)

This is fixed in Python 3.9.1: https://github.com/vispy/vispy/issues/1885

Because my team is stuck an earlier version of Python (lol), I was able to install a monkeypatched wheel with the following modification to `geos.py:load_dll`:
```
    if libname == 'c':
        lib = '/usr/lib/libc.dylib'
    else:
        lib = find_library(libname)
```

One could possibly making this rigorous by checking for MacOS Big Sur

**Comment by iandees** [comment] 2022-01-28 19:08
Thanks. We're stuck on an old version of Python, too.

**Comment by knkumar** [comment] 2022-01-28 19:46
> > Did you get this resolved?
> 
> No. In fact, I tried it again last night and ran into the same problem.

@iandees I patch my pip install with this [commit](https://github.com/shapely/shapely/commit/a34ec59a7dc9089a71968c6871e29addd872ea3b) 

Edit the `geos.py` file in `<python-path>/site-packages/Shapely/geos.py` and change according to the commit from the link replacing 
`free = load_dll('c').free` with `free = CDLL(None).free` letting the linker figure it out as in the comments.

Hope this helps.

**Closed** 2022-02-16 20:31 UTC
Labels: bug

**Comment by peitili** [comment] 2022-09-07 19:02
I am facing this issue after following the suggestions in this thread.  And this is my history of commands and results. I am using Apple M1 machine.

```
11:53:39 pli2@L4YFX2793J ~ → which python
/usr/local/bin/python

11:53:43 pli2@L4YFX2793J ~ → ls -all /usr/local/bin/python
lrwxr-xr-x  1 root  wheel  68 Aug 24 11:52 /usr/local/bin/python -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/python

11:53:49 pli2@L4YFX2793J ~ → which pip
/usr/local/bin/pip

11:53:52 pli2@L4YFX2793J ~ → ls -all /usr/local/bin/pip
lrwxrwxr-x  1 root  admin  65 Aug 24 11:53 /usr/local/bin/pip -> ../../../Library/Frameworks/Python.framework/Versions/2.7/bin/pip

11:53:58 pli2@L4YFX2793J ~ → brew install geos
Running `brew update --auto-update`...
==> Downloading https://ghcr.io/v2/homebrew/core/geos/manifests/3.11.0
Already downloaded: /Users/pli2/Library/Caches/Homebrew/downloads/176dbf09e5a45e25f09c5efd4516d1a1aca6e53d1984eec4f6054a90c9ced2ed--geos-3.11.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/geos/blobs/sha256:25dce9a65e623bc866fc0fdf21be70d2939f33d8f23abc275932e5f3804470c7
Already downloaded: /Users/pli2/Library/Caches/Homebrew/downloads/cd76f477ce3229581c5b87debcb8583610ee754f8fd786d0fcdb2158e75e3f38--geos--3.11.0.arm64_monterey.bottle.tar.gz
==> Pouring geos--3.11.0.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/geos/3.11.0: 463 files, 11MB
==> Running `brew cleanup geos`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

11:54:20 pli2@L4YFX2793J ~ → ls -all /opt/homebrew/opt/geos/lib/
total 15904
drwxr-xr-x  11 pli2  admin      352 Sep  7 11:54 .
drwxr-xr-x  11 pli2  admin      352 Sep  7 11:54 ..
drwxr-xr-x   3 pli2  admin       96 Jul  1 09:42 cmake
-rw-r--r--   1 pli2  admin  2218272 Sep  7 11:54 libgeos.3.11.0.dylib
-r--r--r--   1 pli2  admin  5338552 Jul  1 09:42 libgeos.a
lrwxr-xr-x   1 pli2  admin       20 Jul  1 09:42 libgeos.dylib -> libgeos.3.11.0.dylib
-r--r--r--   1 pli2  admin   279536 Sep  7 11:54 libgeos_c.1.17.0.dylib
lrwxr-xr-x   1 pli2  admin       22 Jul  1 09:42 libgeos_c.1.dylib -> libgeos_c.1.17.0.dylib
-r--r--r--   1 pli2  admin   297720 Jul  1 09:42 libgeos_c.a
lrwxr-xr-x   1 pli2  admin       17 Jul  1 09:42 libgeos_c.dylib -> libgeos_c.1.dylib
drwxr-xr-x   3 pli2  admin       96 Sep  7 11:54 pkgconfig

11:54:43 pli2@L4YFX2793J ~ → export DYLD_LIBRARY_PATH=/opt/homebrew/opt/geos/lib/

11:55:18 pli2@L4YFX2793J ~ → pip install shapely
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Looking in indexes: https://pypi.org/simple, https://pli2:****@company.jfrog.io/company/api/pypi/pypi-local/simple
Collecting shapely
  Using cached Shapely-1.7.1.tar.gz (383 kB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zg/yzz549n96yd7gytzv01btj1c0000gn/T/pip-install-xUQ248/shapely/setup.py'"'"'; __file__='"'"'/private/var/folders/zg/yzz549n96yd7gytzv01btj1c0000gn/T/pip-install-xUQ248/shapely/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/zg/yzz549n96yd7gytzv01btj1c0000gn/T/pip-pip-egg-info-3Udd72
         cwd: /private/var/folders/zg/yzz549n96yd7gytzv01btj1c0000gn/T/pip-install-xUQ248/shapely/
    Complete output (18 lines):
    cannot open shared object from 'geos-config --clibs': '-L/opt/homebrew/Cellar/geos/3.11.0/lib -lgeos_c'
    there were 3 guess(es) for this path:
    	/opt/homebrew/Cellar/geos/3.11.0/lib/libgeos_c.dylib
    	/opt/homebrew/Cellar/geos/3.11.0/lib/geos_c.dylib
    	/opt/homebrew/Cellar/geos/3.11.0/lib/geos_c.framework/geos_c
    Failed `CDLL(/opt/homebrew/opt/geos/lib/libgeos_c.dylib)`
    Failed `CDLL(/Library/Frameworks/GEOS.framework/Versions/Current/GEOS)`
    Failed `CDLL(/opt/local/lib/libgeos_c.dylib)`
    Failed `CDLL(/usr/local/lib/libgeos_c.dylib)`
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zg/yzz549n96yd7gytzv01btj1c0000gn/T/pip-install-xUQ248/shapely/setup.py", line 85, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "shapely/_buildcfg.py", line 190, in <module>
        lgeos = load_dll('geos_c', fallbacks=alt_paths)
      File "shapely/_buildcfg.py", line 164, in load_dll
        libname, fallbacks or []))
    OSError: Could not find library geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib', '/usr/local/lib/libgeos_c.dylib']
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
11:55:34 pli2@L4YFX2793J ~ → sudo ln -s /opt/homebrew/opt/geos/lib/libgeos_c.dylib /usr/local/lib
Password:
11:56:25 pli2@L4YFX2793J ~ → pip install shapely
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Looking in indexes: https://pypi.org/simple, https://pli2:****@company.jfrog.io/company/api/pypi/pypi-local/simple
Collecting shapely
  Using cached Shapely-1.7.1.tar.gz (383 kB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zg/yzz549n96yd7gytzv01btj1c0000gn/T/pip-install-yyhgi5/shapely/setup.py'"'"'; __file__='"'"'/private/var/folders/zg/yzz549n96yd7gytzv01btj1c0000gn/T/pip-install-yyhgi5/shapely/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/zg/yzz549n96yd7gytzv01btj1c0000gn/T/pip-pip-egg-info-S1ljDf
         cwd: /private/var/folders/zg/yzz549n96yd7gytzv01btj1c0000gn/T/pip-install-yyhgi5/shapely/
    Complete output (18 lines):
    cannot open shared object from 'geos-config --clibs': '-L/opt/homebrew/Cellar/geos/3.11.0/lib -lgeos_c'
    there were 3 guess(es) for this path:
    	/opt/homebrew/Cellar/geos/3.11.0/lib/libgeos_c.dylib
    	/opt/homebrew/Cellar/geos/3.11.0/lib/geos_c.dylib
    	/opt/homebrew/Cellar/geos/3.11.0/lib/geos_c.framework/geos_c
    Failed `CDLL(/opt/homebrew/opt/geos/lib/libgeos_c.dylib)`
    Failed `CDLL(/Library/Frameworks/GEOS.framework/Versions/Current/GEOS)`
    Failed `CDLL(/opt/local/lib/libgeos_c.dylib)`
    Failed `CDLL(/usr/local/lib/libgeos_c.dylib)`
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zg/yzz549n96yd7gytzv01btj1c0000gn/T/pip-install-yyhgi5/shapely/setup.py", line 85, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "shapely/_buildcfg.py", line 190, in <module>
        lgeos = load_dll('geos_c', fallbacks=alt_paths)
      File "shapely/_buildcfg.py", line 164, in load_dll
        libname, fallbacks or []))
    OSError: Could not find library geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib', '/usr/local/lib/libgeos_c.dylib']
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

11:56:29 pli2@L4YFX2793J ~ → 
```

**Comment by johnthagen** [comment] 2022-09-07 19:53
>  pip install shapely
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained.

Please use Python 3. Python 2 is end of life and `pip` will pull older versions that don't have ARM wheels published.

```shell
$ python3 -m venv venv
$ ./venv/bin/activate
(venv) $ python -m pip install shapely
```

**Comment by peitili** [comment] 2022-09-07 20:11
> > pip install shapely
> > DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained.
> 
> Please use Python 3. Python 2 is end of life and `pip` will pull older versions that don't have ARM wheels published.
> 
> ```shell
> $ python3 -m venv venv
> $ ./venv/bin/activate
> (venv) $ python -m pip install shapely
> ```

unfortunately we are stuck at Python2 for the moment
