### ISSUE TITLE
Feat: Vectorized orient function

### ISSUE THREAD

**Issue by kylebarron** [shapely/shapely#1684] opened 2022-12-23 16:55 UTC
## Expected behavior and actual behavior.

It looks like the [`shapely.geometry.polygon.orient`](https://shapely.readthedocs.io/en/stable/manual.html#shapely.geometry.polygon.orient) function is not yet vectorized and only works with a single polygon object

## Steps to reproduce the problem.

```
import shapely
xmin = [0, 1]
ymin = [3, 4]
xmax = [5, 6]
ymax = [7, 8]
geoms = shapely.box(xmin, ymin, xmax, ymax, ccw=False)
shapely.geometry.polygon.orient(geoms)
# AttributeError: 'numpy.ndarray' object has no attribute 'exterior'
```

## Operating system

MacOS

## Shapely version and provenance

2.0.0 from pip

**Comment by idanmiara** [comment] 2022-12-25 15:38
Hi @kylebarron 
Please use the new vectorized function `shaply.ops.orient` added in https://github.com/shapely/shapely/pull/1690

**Comment by kylebarron** [comment] 2022-12-25 17:10
It looks like `shapely.ops.orient` is already vectorized as of 2.0, and additionally is already much faster than a python for loop (as we'd expect, so not sure if #1690 is necessary?):

```py
import shapely
xmin = [0, 1]
ymin = [3, 4]
xmax = [5, 6]
ymax = [7, 8]
geoms = shapely.box(xmin, ymin, xmax, ymax, ccw=False)
big_geoms = list(geoms) * 1000

%timeit shapely.ops.orient(big_geoms)
# 313 ns ± 7.58 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

%timeit [shapely.ops.orient(geom) for geom in big_geoms]
# 244 ms ± 4.66 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

I didn't know `shapely.ops.orient` existed; I'll move this to a doc request instead of a feature request. When I [search for `orient`](https://shapely.readthedocs.io/en/stable/search.html?q=orient) in the doc website, the only API doc result is for `shapely.geometry.polygon.orient`. Is there an API doc page in the website for everything in `shapely.ops`? Or is it laid out by intention, not by python module

**Comment by idanmiara** [comment] 2022-12-25 18:20
> It looks like `shapely.ops.orient` is already vectorized as of 2.0

Nope. It's just returns the original geom since it's not supported. just try your original test on it.

> Is there an API doc page in the website for everything in `shapely.ops`? Or is it laid out by intention

There are many duplicated functions from in shapely 2 with fragmented documentation. 
I'm working on improving the docs https://github.com/shapely/shapely/issues/1688

**Comment by kylebarron** [comment] 2022-12-25 19:12
> It's just returns the original geom since it's not supported

Oh that seems really bad: it's silently returning results with no indication that the orient didn't happen

**Comment by idanmiara** [comment] 2022-12-25 20:12
> > It's just returns the original geom since it's not supported
> 
> Oh that seems really bad: it's silently returning results with no indication that the orient didn't happen

I think that the idea was that if the input is not `BaseMultipartGeometry` and not `Polygon` then it's a geometry that is oriented (not sure if that's true). 
Now if you pass something that's not a Geometry, like a geometry array, it could be considered as an invalid input thus the output is unexpected.

With this PR it works also for geometry array.

**Comment by jorisvandenbossche** [comment] 2022-12-28 10:59
Yes, the existing `shapely.ops.orient` was indeed assuming you always pass a single geometry (and passing through anything that has no polygonal parts). But it is certainly unfortunate that it didn't at least check that it receives a geometry, to avoid such confusion. 

Existing issue about providing a vectorized version of this: https://github.com/shapely/shapely/issues/1366

**Comment by jorisvandenbossche** [comment] 2022-12-28 12:33
Duplicate of https://github.com/shapely/shapely/issues/1366

**Closed by jorisvandenbossche** 2022-12-28 12:33 UTC

**Comment by idanmiara** [comment] 2023-01-01 14:43
@kylebarron 
Please see new implementation for ``force_polygon_ccw` in https://github.com/shapely/shapely/pull/1690
I didn't time it, but it is probably a bit faster than old `orient`.
