### ISSUE TITLE
Inheritance from geometries does not work on Shapely 2.0 any more

### ISSUE THREAD

**Issue by felixdivo** [shapely/shapely#1313] opened 2022-02-09 22:32 UTC
## Expected behavior and actual behavior

Expected: Inheriting from geometry objects works like on any other objects

Actual: Starting with 2.0 (as currently developed on the `main` branch), this does not seem to be possible

I am aware that this is only a development "snapshot", but I think this will become a problem. If it is intended to work, I can of course contribute the problematic code as a regression test. However, I do not know of a solution to the actual problem right now.

## Steps to reproduce the problem.

This is a boiled-down example. The multiple inheritance probably isn't really the problem here, it's inheritance in general.

### On Shapely 1.7.1 and before, this worked fine

```python
from abc import ABC
from typing import Any

from shapely.geometry import Polygon

from our_lib import compat_transform


class PrintingMixin(ABC):
    """In reality, this contains common and custom logic for geometries."""

    def __init__(self, name: str) -> None:
        self.name = name

    def print_the_name(self) -> None:
        print(self.name)


class FancyPolygon(PrintingMixin, Polygon):
    """This contains custom attributes and methods, like projection information."""

    def __init__(self, points: Any, name: str = "Name", projection: str = "Projection") -> None:
        PrintingMixin.__init__(self, name)
        Polygon.__init__(self, compat_transform(points))
        self.projection = projection

    def print_the_projection(self) -> None:
        print(self.projection)


points = [(0, 1), (1, 2), (2, 3)]
poly = FancyPolygon(points)
poly.print_the_name()
poly.print_the_projection()
```

### On Shapely 1.8.0

We got the `ShapelyDeprecationWarning: Setting custom attributes on geometry objects is deprecated, and will raise an AttributeError in Shapely 2.0`, as intended. We were confident that we would only need to add slots, which is fairly easy even with multiple inheritance (just the two lines with `__slots__` where changed):

```python
# In PrintingMixin:
__slots__ = ()  # Must be set in subclasses https://docs.python.org/3/reference/datamodel.html#object.__slots__

# In FancyPolygon:
__slots__ = ["name", "projection"]  # Will be merged with Polygon.__slots__
```

This *should*  work once `shapely.Polygon` also has a `__slots__` attribute.
It also works functionally on this version, although it does not suppress the `ShapelyDeprecationWarning`.

### On the way to shapely 2.0 (at commit b47dab627f796e3a89e340a6e533504037535e88)

... we realized, that this might be more complicated than that, since by now, `shapely.Polygon` has a `__new__` class method. This means that `FancyPolygon.__init__(...)` will never actually be called. The implications of that:
- We cannot apply `compat_transform(...)`
- Custom attributes are not initialized
- One gets an `AttributeError: 'Polygon' object has no attribute 'print_the_name'`, since all out custom methods are not callable (since `FancyPolygon(...)` does not return a `FancyPolygon`)

I tried to hack it by adding a custom `__new__()` to `FancyPolygon`, but to no avail (`TypeError: __class__ assignment: 'FancyPolygon' object layout differs from 'Polygon'`:

```python
    def __new__(cls, points, *args, **kwargs):
        import shapely
        poly = shapely.polygons(compat_transform(points))  # This approach also has poor maintainability
        poly.__class__ = FancyPolygon  # <-- error in this line
        return poly
```

## Operating system

Ubuntu 20.04, Python 3.8. Probably a universal problem.

## Shapely version and provenance

Various, see above. Installed with `pip`, the last one with ` python -m pip install git+https://github.com/shapely/shapely@b47dab627f796e3a89e340a6e533504037535e88`.

**Comment by jorisvandenbossche** [comment] 2022-02-09 22:49
Yes, see some related discussion in https://github.com/shapely/shapely/issues/1233. We didn't really consider the subclassing topic upfront, but is certainly is a consequence of the refactor in shapely 2.0.

A general solution could be to use composition instead of inheritance, but in the last comment at https://github.com/shapely/shapely/issues/1233#issuecomment-977837620 it seems @Jeremiah-England found a way to get the subclass working.

**Comment by felixdivo** [comment] 2022-02-09 23:39
Thank you @jorisvandenbossche, that thread looks great!

**Comment by sgillies** [comment] 2022-02-16 19:53
I think we can close this as it's a known issue and intentional, yes?

**Comment by jorisvandenbossche** [comment] 2022-02-16 20:17
Yes, and also as a duplicate of #1233

**Closed by jorisvandenbossche** 2022-02-16 20:17 UTC
