### ISSUE TITLE
[shapely 2] Unexpected warning for simple intersection

### ISSUE THREAD

**Issue by bretttully** [shapely/shapely#1709] opened 2023-01-05 12:05 UTC
## Expected behavior and actual behavior.

Running the following code gives a strange warning

```python
from shapely.geometry import box

p1 = box(0, 0, 1, 1)
p2 = box(0, 2, 1, 3)

i = p1.intersection(p2)
print(f"{i.wkt=}")
```

Output:

```bash
/opt/conda/lib/python3.10/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
i.wkt='POLYGON EMPTY'
```

## Steps to reproduce the problem.

Here is a Dockerfile

```
FROM mambaorg/micromamba:jammy as build-stage
RUN micromamba install --name base --yes --channel conda-forge \
    "python 3.10.*" \
    "shapely >=2.0"
ARG MAMBA_DOCKERFILE_ACTIVATE=1
RUN python -c "from shapely.geometry import box; p1 = box(0, 0, 1, 1); p2 = box(0, 2, 1, 3); i = p1.intersection(p2); print(f'{i.wkt=}')"
```

Running with `docker build --progress plain -f debugging.Dockerfile .` gives:

<details>

<summary>Output</summary>

```
#1 [internal] load build definition from debugging.Dockerfile
#1 sha256:00b07bd6960201cc4f6115e55efd0046bfa5d1ad57b0f17636fa39019a8226e9
#1 transferring dockerfile: 54B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:1290880ac1dee60249526a73eda2cfa4186bb29b72c0357fe140aa88aaf120b9
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/mambaorg/micromamba:jammy
#3 sha256:70f396090a53ab9b6a069cc5d6d0672a0924b076e550e08e2f4c414e429987cc
#3 DONE 2.2s

#4 [1/3] FROM docker.io/mambaorg/micromamba:jammy@sha256:3e3d2899397fb031d57d4269a19f7700d4eb72e802d1d1b8f6054acd93b6fe47
#4 sha256:4a94cba5ef489da4fe85e3887c63904a40cb788f5ac27ff5dff6a4f3998815af
#4 CACHED

#5 [2/3] RUN micromamba install --name base --yes --channel conda-forge     "python 3.10.*"     "shapely >=2.0"
#5 sha256:12fa428ad4fe3844995127364b6790624c1b4fd407b24624af353ed1792b0b4c
#5 0.243
#5 0.243                                            __
#5 0.243           __  ______ ___  ____ _____ ___  / /_  ____ _
#5 0.243          / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
#5 0.243         / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
#5 0.243        / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
#5 0.243       /_/
#5 0.243
#5 20.70
#5 20.70 Transaction
#5 20.70
#5 20.70   Prefix: /opt/conda
#5 20.70
#5 20.70   Updating specs:
#5 20.70
#5 20.70    - python=3.10
#5 20.70    - shapely[version='>=2.0']
#5 20.70
#5 20.70
#5 20.71   Package               Version  Build                Channel                   Size
#5 20.71 ──────────────────────────────────────────────────────────────────────────────────────
#5 20.71   Install:
#5 20.71 ──────────────────────────────────────────────────────────────────────────────────────
#5 20.71
#5 20.71   + _libgcc_mutex           0.1  conda_forge          conda-forge/linux-64       3kB
#5 20.71   + _openmp_mutex           4.5  2_gnu                conda-forge/linux-64      24kB
#5 20.71   + bzip2                 1.0.8  h7f98852_4           conda-forge/linux-64     496kB
#5 20.71   + ca-certificates   2022.12.7  ha878542_0           conda-forge/linux-64     146kB
#5 20.71   + geos                 3.11.1  h27087fc_0           conda-forge/linux-64       2MB
#5 20.71   + ld_impl_linux-64       2.39  hcc3a1bd_1           conda-forge/linux-64     691kB
#5 20.71   + libblas               3.9.0  16_linux64_openblas  conda-forge/linux-64      13kB
#5 20.71   + libcblas              3.9.0  16_linux64_openblas  conda-forge/linux-64      13kB
#5 20.71   + libffi                3.4.2  h7f98852_5           conda-forge/linux-64      58kB
#5 20.71   + libgcc-ng            12.2.0  h65d4601_19          conda-forge/linux-64     954kB
#5 20.71   + libgfortran-ng       12.2.0  h69a702a_19          conda-forge/linux-64      23kB
#5 20.71   + libgfortran5         12.2.0  h337968e_19          conda-forge/linux-64       2MB
#5 20.71   + libgomp              12.2.0  h65d4601_19          conda-forge/linux-64     466kB
#5 20.71   + liblapack             3.9.0  16_linux64_openblas  conda-forge/linux-64      13kB
#5 20.71   + libnsl                2.0.0  h7f98852_0           conda-forge/linux-64      31kB
#5 20.71   + libopenblas          0.3.21  pthreads_h78a6416_3  conda-forge/linux-64      11MB
#5 20.71   + libsqlite            3.40.0  h753d276_0           conda-forge/linux-64     810kB
#5 20.71   + libstdcxx-ng         12.2.0  h46fd767_19          conda-forge/linux-64       4MB
#5 20.71   + libuuid              2.32.1  h7f98852_1000        conda-forge/linux-64      28kB
#5 20.71   + libzlib              1.2.13  h166bdaf_4           conda-forge/linux-64      66kB
#5 20.71   + ncurses                 6.3  h27087fc_1           conda-forge/linux-64       1MB
#5 20.71   + numpy                1.24.1  py310h08bbf29_0      conda-forge/linux-64       7MB
#5 20.71   + openssl               3.0.7  h0b41bf4_1           conda-forge/linux-64       3MB
#5 20.71   + pip                  22.3.1  pyhd8ed1ab_0         conda-forge/noarch         2MB
#5 20.71   + python               3.10.8  h4a9ceb5_0_cpython   conda-forge/linux-64      23MB
#5 20.71   + python_abi             3.10  3_cp310              conda-forge/linux-64       6kB
#5 20.71   + readline              8.1.2  h0f457ee_0           conda-forge/linux-64     298kB
#5 20.71   + setuptools           65.6.3  pyhd8ed1ab_0         conda-forge/noarch       634kB
#5 20.71   + shapely               2.0.0  py310h8b84c32_0      conda-forge/linux-64     421kB
#5 20.71   + tk                   8.6.12  h27826a3_0           conda-forge/linux-64       3MB
#5 20.71   + tzdata                2022g  h191b570_0           conda-forge/noarch       108kB
#5 20.71   + wheel                0.38.4  pyhd8ed1ab_0         conda-forge/noarch        33kB
#5 20.71   + xz                    5.2.6  h166bdaf_0           conda-forge/linux-64     418kB
#5 20.71
#5 20.71   Summary:
#5 20.71
#5 20.71   Install: 33 packages
#5 20.71
#5 20.71   Total download: 63MB
#5 20.71
#5 20.71 ──────────────────────────────────────────────────────────────────────────────────────
#5 20.71
#5 20.71
#5 20.71
#5 20.71 Transaction starting
#5 27.69 Linking _libgcc_mutex-0.1-conda_forge
#5 27.69 Linking python_abi-3.10-3_cp310
#5 27.69 Linking ld_impl_linux-64-2.39-hcc3a1bd_1
#5 27.69 Linking ca-certificates-2022.12.7-ha878542_0
#5 27.69 Linking libstdcxx-ng-12.2.0-h46fd767_19
#5 27.70 Linking libgfortran5-12.2.0-h337968e_19
#5 27.70 Linking libgomp-12.2.0-h65d4601_19
#5 27.70 Linking libgfortran-ng-12.2.0-h69a702a_19
#5 27.70 Linking _openmp_mutex-4.5-2_gnu
#5 27.70 Linking libgcc-ng-12.2.0-h65d4601_19
#5 27.71 Linking libuuid-2.32.1-h7f98852_1000
#5 27.71 Linking libopenblas-0.3.21-pthreads_h78a6416_3
#5 27.71 Linking openssl-3.0.7-h0b41bf4_1
#5 27.74 Linking ncurses-6.3-h27087fc_1
#5 29.39 Linking libffi-3.4.2-h7f98852_5
#5 29.39 Linking bzip2-1.0.8-h7f98852_4
#5 29.39 Linking geos-3.11.1-h27087fc_0
#5 29.45 Linking xz-5.2.6-h166bdaf_0
#5 29.51 Linking libzlib-1.2.13-h166bdaf_4
#5 29.51 Linking libnsl-2.0.0-h7f98852_0
#5 29.51 Linking libblas-3.9.0-16_linux64_openblas
#5 29.68 Linking readline-8.1.2-h0f457ee_0
#5 29.68 Linking tk-8.6.12-h27826a3_0
#5 29.73 Linking libsqlite-3.40.0-h753d276_0
#5 29.74 Linking libcblas-3.9.0-16_linux64_openblas
#5 29.91 Linking liblapack-3.9.0-16_linux64_openblas
#5 30.08 Linking tzdata-2022g-h191b570_0
#5 30.12 Linking python-3.10.8-h4a9ceb5_0_cpython
#5 30.48 Linking wheel-0.38.4-pyhd8ed1ab_0
#5 30.70 Linking setuptools-65.6.3-pyhd8ed1ab_0
#5 30.73 Linking pip-22.3.1-pyhd8ed1ab_0
#5 30.80 Linking numpy-1.24.1-py310h08bbf29_0
#5 31.04 Linking shapely-2.0.0-py310h8b84c32_0
#5 31.19 Transaction finished
#5 DONE 32.2s

#6 [3/3] RUN python -c "from shapely.geometry import box; p1 = box(0, 0, 1, 1); p2 = box(0, 2, 1, 3); i = p1.intersection(p2); print(f'{i.wkt=}')"
#6 sha256:f718ddd103a34ea0575856c9b9b34fbf982688a992c5a7d8c3eaf49b1bb2591d
#6 0.415 /opt/conda/lib/python3.10/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
#6 0.415   return lib.intersection(a, b, **kwargs)
#6 0.415 i.wkt='POLYGON EMPTY'
#6 DONE 0.4s

#7 exporting to image
#7 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#7 exporting layers
#7 exporting layers 7.8s done
#7 writing image sha256:c21470e9cccc183f8126e36fff52be0abe13bad0e658936c9341faf7fbfb3be4 done
#7 DONE 7.9s
```

</details>

## Other information

Setting `grid_size=1` in the intersection call makes the error message go away

**Comment by jorisvandenbossche** [comment] 2023-01-05 12:54
See also https://github.com/shapely/shapely/issues/1552#issuecomment-1259429629 and the linked issues for some context.

The problem is that some code in GEOS causes floating point error flags to be set, and then the numpy ufunc machinery picks this up and generates those warnings. 

We should maybe look into whether we can clear those flags in the c code after calling a GEOS function and before returning to numpy land.

**Comment by jorisvandenbossche** [comment] 2023-01-05 13:06
I suppose the numpy C API has some features that we could use for this: https://numpy.org/doc/stable/reference/c-api/coremath.html#low-level-floating-point-manipulation

cc @caspervdw

**Comment by bretttully** [comment] 2023-01-05 22:18
Running at scale, and we're getting a lot of these clogging up our logging. Can you see any harm in a temp solution of filtering the warnings?

```python
warnings.filterwarnings("ignore", message="invalid value encountered in intersection")
```

**Comment by caspervdw** [comment] 2023-01-07 12:11
It is unfortunate that these warnings now pop up, but I don't think that it is a good idea for us to hide the fact that these flags are set by GEOS. It should be fixed upstream.

I usually use `numpy.seterr(invalid="ignore")` to hide these message when they pop up and I am sure that I am not doing anything wrong (https://numpy.org/doc/stable/reference/generated/numpy.seterr.html#numpy-seterr)

**Comment by jorisvandenbossche** [comment] 2023-01-07 14:33
> It should be fixed upstream.

Ideally yes, but it's a bit problematic if upstream devs tried and don't know how to fix it (cfr https://github.com/libgeos/geos/issues/515)

The main reason why I would consider hiding this on our side is because up to now, I haven't yet seen any example where those warnings are actually actionable (that indicates something that you can do as a user). As a consequence, they are IMO just confusing. And while it is indeed easy to ignore/hide them (either with numpy's API or with generic filterwarnings), I am not sure it is needed to expect from every user to do this (and to know it is OK to do this)

**Comment by jorisvandenbossche** [comment] 2023-01-07 18:26
> I haven't yet seen any example where those warnings are actually actionable

I suppose when you accidentally got NaNs in your coordinates, that would be a valid reason to get warnings (although even then the warning is not super clear about what the issue is)

Anyway, for this specific case (the example in the top post, intersection of non-overlapping polygons), I took a quick look in GEOS and here it was actually easy to track down and fix -> https://github.com/libgeos/geos/pull/790

**Comment by jorisvandenbossche** [comment] 2023-01-14 19:24
This is fixed in upstream GEOS main (https://github.com/libgeos/geos/pull/791), and also backported to 3.10 / 3.11. So once there is a new release of any of those versions, the warnings should go away.

**Closed** 2023-01-23 20:33 UTC
