### ISSUE TITLE
minimum_rotated_rectangle is incorrect in 2.0.0

### ISSUE THREAD

**Issue by sdoose** [shapely/shapely#1670] opened 2022-12-16 07:09 UTC
## Expected behavior and actual behavior.

In shapely 2.0.0 the following code produces an incorrect
minimum_rotated_rectangle with area=20.4 when it should be 20.

In shapely <2.0.0 the correct minimum_rotated_rectangle with area=20 is found.

## Steps to reproduce the problem.
```python
"""
In shapely 2.0.0 the following code produces an incorrect
minimum_rotated_rectangle with area=20.4 and raises:

>       assert new_minimum_rotated_rectangle.area == true_minimum_rotated_rectangle.area
E       assert 20.400000000000006 == 20.0
E        +  where 20.400000000000006 = <POLYGON ((5.1 5.3, 1.5 6.5, -0.2 1.4, 3.4 0.2, 5.1 5.3))>.area
E        +  and   20.0 = <POLYGON ((1 1, 1 6, 5 6, 5 1, 1 1))>.area
bug_in_2_0_0.py:32: AssertionError
"""
import numpy as np
import matplotlib.pyplot as plt
from shapely.geometry import MultiPoint, Polygon

def test_minimum_rotated_rectangle():
    points = np.array(
        [[1, 1], [1, 5], [3, 6], [4, 2], [5, 5]]
    )
    pts = MultiPoint(points)
    new_minimum_rotated_rectangle = pts.minimum_rotated_rectangle

    true_minimum_rotated_rectangle = Polygon([[1, 1], [1, 6], [5, 6], [5, 1]])

    fig, ax = plt.subplots(nrows=1, ncols=1, figsize=(5, 5))
    ax.plot(*points.T, c="red", marker=".")
    ax.plot(*np.array(new_minimum_rotated_rectangle.boundary.coords).T,
            c="green", marker="o", alpha=0.2
            )
    ax.plot(*np.array(true_minimum_rotated_rectangle.boundary.coords).T,
            c="blue", marker="X", alpha=0.2
            )
    ax.set(xlim=(0, 10), ylim=(0, 10))
    plt.show()

    print(true_minimum_rotated_rectangle.area)
    print(true_minimum_rotated_rectangle.boundary)
    print(new_minimum_rotated_rectangle.area)
    print(new_minimum_rotated_rectangle.boundary)
    assert new_minimum_rotated_rectangle.area == true_minimum_rotated_rectangle.area
```

## Operating system

Ubuntu, MacOS, Windows

## Shapely version and provenance

Shapely 2.0.0 installed from PyPI using pip or from conda-forge using mamba.

**Comment by jorisvandenbossche** [comment] 2022-12-17 10:07
@sdoose thanks a lot for the report!

I rewrote your nice reproducible example a bit (and using WKT for construction, which is easier to potentially report this upstream to GEOS):

```python
import shapely
pts = shapely.from_wkt("MULTIPOINT (1 1, 1 5, 3 6, 4 2, 5 5)")

minimum_rotated_rectangle = pts.minimum_rotated_rectangle
true_minimum_rotated_rectangle = shapely.from_wkt("POLYGON ((1 1, 1 6, 5 6, 5 1, 1 1))")
```

```
>>> minimum_rotated_rectangle
<POLYGON ((5.1 5.3, 1.5 6.5, -0.2 1.4, 3.4 0.2, 5.1 5.3))>
>>> true_minimum_rotated_rectangle
<POLYGON ((1 1, 1 6, 5 6, 5 1, 1 1))>
>>> minimum_rotated_rectangle.area
20.400000000000006
>>> true_minimum_rotated_rectangle.area
20.0
```

And plotting this (with the new helpers in shapely 2.0):

```
from shapely.plotting import plot_line, plot_points
plot_points(pts, zorder=10)
plot_line(minimum_rotated_rectangle.boundary, color="green", alpha=0.5)
plot_line(true_minimum_rotated_rectangle.boundary, color="red", alpha=0.5)
```

![shapely_minimum_rotated_rectangle](https://user-images.githubusercontent.com/1020496/208236173-76ba0052-4bcd-466b-9d9e-4d2d4a900095.png)

----

So what changed in shapely 2.0.0 is that we now rely on the GEOS implementation for this (`GEOSMinimumRotatedRectangle`), while before in shapely 1.8.x we had a custom implementation. See https://github.com/shapely/shapely/pull/1532 for the PR that changed this. 

So while I assumed the results would be the same, this is clearly not always the case. Looking at the GEOS explanation of that method, it mentions that the resulting _"rectangle has width equal to the minimum diameter, and a longer length"_. And looking at the implementation, it indeed seems to be based on an implementation that first determines the "minimum diameter" of the input geometry (https://github.com/libgeos/geos/blob/2d931f06b34aee60d9a22a9d697610afd9046ee9/capi/geos_ts_c.cpp#L1304-L1305).
Quoting the doc comment of this [MinimumDiameter class](https://github.com/libgeos/geos/blob/2d931f06b34aee60d9a22a9d697610afd9046ee9/include/geos/algorithm/MinimumDiameter.h#L42-L63):

> The minimum diameter is defined to be the width of the smallest band that
> contains the geometry, where a band is a strip of the plane defined
> by two parallel lines. This can be thought of as the smallest hole
> that the geometry can be moved through, with a single rotation.

And the resulting minimum_rotated_rectangle does have a smaller width (but not a smaller area):

```
>>> minimum_rotated_rectangle
<POLYGON ((5.1 5.3, 1.5 6.5, -0.2 1.4, 3.4 0.2, 5.1 5.3))>
>>> Point(-0.2, 1.4).distance(Point(3.4, 0.2))
3.794733192202055

>>> true_minimum_rotated_rectangle
<POLYGON ((1 1, 1 6, 5 6, 5 1, 1 1))>
>>> Point(1, 1).distance(Point(5, 1))
4.0
```

But so it seems that this logic of first finding the minimum width, does not necessarily result in the minimum area rectangle. I am not fully sure what the guarantees that `GEOSMinimumRotatedRectangle` wants to give on that front (i.e. minimum width vs minimum area).

**Comment by sdoose** [comment] 2022-12-19 17:07
Thank you for your reasonable explanation. My remaining question would be, what sort of minimum rotated rectangle (width or area) will shapely want to provide? Maybe, keeping the old implementation in addition to a wrapper for GEOSMinimumRotatedRectangle is feasible?

**Comment by dr-jts** [comment] 2023-01-02 01:14
The GEOS **Minimum Rotated Rectangle** algorithm is incorrect (see https://github.com/libgeos/geos/issues/679).  Hopefully this will get fixed soon (in 2023, probably).

**Comment by idanmiara** [comment] 2023-01-05 08:11
I would think that we should restore the custom implementation from Shapely 1.8 and maybe add a flag with 2 options:
1. use the custom implementation (default)
2. use geos function
We can consider changing the default once the issue is fixed upstream.

Another option maybe worth exploring is translating to python [the other suggested workaround](https://github.com/libgeos/geos/issues/679#issuecomment-1249096016)

**Comment by martinfleis** [comment] 2023-01-26 19:19
I've noticed it back when I exposed `minimum_bounding_rectangle` in pygeos in https://github.com/pygeos/pygeos/pull/314#issuecomment-800332713. Back then my conclusion was that the two are different but not necessarily that one is the correct one and the other is wrong since as you can see in that PR, in some cases the old shapely version is smaller but in other GEOS is.

I now assume that the GEOS implementation is actually not ideal but from the perspective of my use cases, I often prefer to have very fast approximation (GEOS version) than precise but slow algorithm as that may create a bottleneck. So if there's anything to do in shapely now, I would vote to expose both in some way, certainly not to replace the GEOS implementation with the pure python we had before. I'd see it as a regression in some of the workflows I use.

**Comment by idanmiara** [comment] 2023-01-26 21:01
>  certainly not to replace the GEOS implementation with the pure python we had before.

currently there are two names for the same function: `minimum_rotated_rectangle` = `oriented_envelope`
I suggest we decide if to assign the fast GEOS implementation or the pure python exact implementation (#1708) with those names and set a new name for the other implementation.

**Comment by jorisvandenbossche** [comment] 2023-01-26 21:33
This is of course very much data dependent, but I did an experiment with the NYC Building Footprints open data consisting of around 1 million polygons. 
Calcuting the minimum_rotated_rectangle for each of those takes ~5s with current shapely (the GEOS implementation), and ~8min with the old shapely implementation (using the branch of https://github.com/shapely/shapely/pull/1708).

On average, the old implementation gives smaller results, but for 97% of the cases the difference is within -0.1% / +0.1% difference.

So that's a significant perf difference, for a limited (depending on the needs of your use case, obviously) difference in result. That seems to be a good reason to consider exposing both.

Out of curiosity, plotting the one with the biggest difference:

![hist_diff_outlier](https://user-images.githubusercontent.com/1020496/214954897-393c445c-9a8f-4ec7-a734-a0713d7eaa05.png)

**Comment by jorisvandenbossche** [comment] 2023-01-26 21:47
Of course, part of the reason that GEOS is faster because the current algorithm is too simple, and so also a fixed version in GEOS later on will probably be slower (a large part of the slowdown is still the overhead of doing it in python though)

**Comment by idanmiara** [comment] 2023-01-27 09:20
@jorisvandenbossche are you suggesting exposing the python implementation under a new name ?

**Comment by brendan-ward** [comment] 2023-01-27 16:39
I haven't had time to fully engage on this yet or look closely at the associated PR, but I have cases similar to @martinfleis where I need rotated rectangles to be fast but not necessarily perfect.

Using different function names doesn't feel right here, esp. once this gets updated in GEOS, unless that fix gets assigned to a totally different CAPI function.

I wonder if we can put this in a parameter instead?  That way we can keep `minimum_rotated_rectangle` and `oriented_envelope` as aliases, but toggle behavior based on the parameter, and it would enable using the fastest by default - which seems OK for the majority of cases - and opt-in to the slower more precise behavior.

Something like 

```Python
minimum_rotated_rectangle(geometries, mode="fast")  # default
minimum_rotated_rectangle(geometries, mode="min_area")
```

The question would then be if the fixed GEOS version produces identical results as the python version here, if these parameters basically become meaningless from that version of GEOS onward because they'd use the same backend implementation (i.e., drop the python version).

**Comment by jorisvandenbossche** [comment] 2023-01-27 16:54
I think I would also prefer a keyword, given that there is otherwise not a good reason for which of `minimum_rotated_rectangle` or `oriented_envelope` should have which behaviour ("minimum_rotated_rectangle" is the name from GEOS but so currently doesn't give "minimum" rectangles, and "oriented_envelope" is what PostGIS uses but with the same behaviour as GEOS ..).

For a parameter, we could maybe use `mode="minimum_diameter"` (or `method=".."`?), because that is actually the method that GEOS currently uses, and avoids a connotation like "fast" (which could change in the future). We can of course still mention in the docstring that right now this method is faster. 

We could also give the default no name (`mode=None`), to avoid that people would start using the explicit name that will get useless in the future.

> The question would then be if the fixed GEOS version produces identical results as the python version here, if these parameters basically become meaningless from that version of GEOS onward because they'd use the same backend implementation (i.e., drop the python version).

Yes, but I think that is not too bad as the "price" to pay, we can keep the parameter as a no-op for a while and start warning about it at some point.

**Comment by brendan-ward** [comment] 2023-01-27 17:01
> give the default no name (mode=None)

I like this option; it is shorthand for "use whatever is implemented in this version of GEOS" (which we explain in more detail in the docstring) - unless the different method in GEOS gets exposed as a different CAPI function; otherwise behavior is GEOS version-dependent.

Otherwise, a more descriptive parameter name is better, like
> we could maybe use mode="minimum_diameter" (or method=".."?)

`"fast"` was just all I could think of at the moment.

**Comment by idanmiara** [comment] 2023-01-27 17:14
> > give the default no name (mode=None)
> 
> I like this option; it is shorthand for "use whatever is implemented in this version of GEOS" (which we explain in more detail in the docstring) - unless the different method in GEOS gets exposed as a different CAPI function; otherwise behavior is GEOS version-dependent.
> 
> Otherwise, a more descriptive parameter name is better, like
> 
> > we could maybe use mode="minimum_diameter" (or method=".."?)
> 
> `"fast"` was just all I could think of at the moment.

how about `exact: bool = False` ?

**Comment by martinfleis** [comment] 2023-01-27 18:09
I like the keyword solution defaulting to None and GEOS. I wouldn't use `exact` though because as I mentioned above, neither algo is always smaller, so you can't claim that one is exact.

**Comment by idanmiara** [comment] 2023-01-27 18:36
OK, I don't have any strong preference.
I could modify https://github.com/shapely/shapely/pull/1708 once there is a conclusion

**Comment by jorisvandenbossche** [comment] 2023-01-27 18:50
> > give the default no name (mode=None)
> 
> I like this option; it is shorthand for "use whatever is implemented in this version of GEOS"

> I like the keyword solution defaulting to None and GEOS.

In my head the idea would be that the default is still the original (1.x) shapely version? So the default of None would be "use whatever shapely currently think is best", and in the future that might change to use the GEOS version if that gets fixed. 

That preserves behaviour compared to shapely 1.8, and still gives the option to pass `method="minimum_diameter"` (or different naming) for the people that prefer the currently faster method.

**Comment by idanmiara** [comment] 2023-02-01 06:24
> > > give the default no name (mode=None)
> > 
> > 
> > I like this option; it is shorthand for "use whatever is implemented in this version of GEOS"
> 
> > I like the keyword solution defaulting to None and GEOS.
> 
> In my head the idea would be that the default is still the original (1.x) shapely version? So the default of None would be "use whatever shapely currently think is best", and in the future that might change to use the GEOS version if that gets fixed.
> 
> That preserves behaviour compared to shapely 1.8, and still gives the option to pass `method="minimum_diameter"` (or different naming) for the people that prefer the currently faster method.

Rebased and done https://github.com/shapely/shapely/pull/1708

**Comment by sgillies** [comment] 2023-06-15 18:09
GEOS changed the minimum rotated rectangle algorithm 3 weeks ago: https://github.com/libgeos/geos/commit/2efd5ed41009149db31b896cea98aacf765b004c. I think that's the most likely explanation for the CI failures like this one: https://github.com/shapely/shapely/actions/runs/5252887855/jobs/9489511175#step:16:185.

@jorisvandenbossche @martinfleis @idanmiara @sdoose if GEOS's new algorithm satisfies us then doing nothing other than relaxing the test assertions (to assert only that the result is a rectangle, even) is an option for us.

**Comment by ferreteleco** [comment] 2023-08-04 14:18
Any updates on this?

**Comment by jorisvandenbossche** [comment] 2023-10-08 10:31
Moving some relevant comments from @caspervdw from https://github.com/shapely/shapely/pull/1885#issuecomment-1721156055 here (that PR updated the tests to follow the new behaviour with 3.12):

> I have been reading up on https://github.com/shapely/shapely/issues/1670 and https://github.com/shapely/shapely/pull/1708 considering the backwards incompatible change in `oriented_envelope` in GEOS 3.12
>
> My personal opinion is that shapely shouldn't attempt to cover up backwards incompatible changes in GEOS. We should do nothing short of documenting that it happened. 
>
> In this specific case we already had a solution in Shapely 1.x, so porting that back for GEOS 3.11 users could be done, however I think it is a very small user base that doesn't want to go forward to GEOS 3.12 so I think it is better to go forward and not fix anything at all.

**Comment by jorisvandenbossche** [comment] 2023-10-08 10:33
And @mwtoews's reponse there:

> As for the approaches to upstream changes impacting oriented_envelope I'm inclined to go for an easier option of not covering up GEOS' changes and documenting behaviours.

**Comment by jorisvandenbossche** [comment] 2023-10-08 10:38
> My personal opinion is that shapely shouldn't attempt to cover up backwards incompatible changes in GEOS. We should do nothing short of documenting that it happened.

I certainly agree in general, but that isn't the full story here: the backwards incompatible change in shapely 2.0.0 was not caused by GEOS, it was caused by us removing our own implementation, and so (inadvertently) causing this change assuming the behaviour of the GEOS function was the same.

So fixing this is rather covering up our own backwards incompatible change, and it's GEOS change that will actually allow us to switch to the GEOS implementation based on the GEOS version. 
In our C code, we have several `#if` checks on the GEOS version, providing our own fallback implementation for older GEOS versions, and using a GEOS function for newer versions, where this exists or works correctly. The proposal here is to do something similar, but only on the Python side.

**Comment by jorisvandenbossche** [comment] 2023-10-08 11:18
For illustration, I updated https://github.com/shapely/shapely/pull/1708/files to just fallback to our own implementation for older GEOS (so removing the keyword to control this). This ensures consistent behaviour for `minimum_rotated_rectangle` both across shapely versions as GEOS versions.

**Comment by jorisvandenbossche** [comment] 2023-10-09 06:40
On https://github.com/shapely/shapely/issues/1670#issuecomment-1607101266:

> The question then is whether it is still worth adding a custom keyword for this, though (someone who wants the speed and not the precise result, can ensure they have GEOS 3.12 installed. Although eg for users installing with pip, that won't yet be possible on the short term (assuming we would keep 2.0.x wheels bundled with GEOS 3.11.x, and do shapely 2.1.x with GEOS 3.12))

For the updated version of https://github.com/shapely/shapely/pull/1708 that I would like to include in the release, I removed the `method` keyword, given that it's not something we would like to keep long term, and the latest GEOS already provides the fast option. 
Conda users will already have GEOS 3.12 when installing shapely 2.0.2, and for pip users we will hopefully have a shapely 2.1 in some time (for those users, it's a temporary step back in performance, but also only for a new feature of 2.0, not compared to 1.8)

**Closed** 2023-10-12 18:36 UTC
