### ISSUE TITLE
Invalid Polygon constructed from valid LinearRing

### ISSUE THREAD

**Issue by jpmaterial** [shapely/shapely#1271] opened 2021-12-22 17:30 UTC
I'm constructing a Polygon by passing a single LinearRing as the only argument to the constructor.

## Expected behavior and actual behavior.

In the outlined scenario, I expect the Polygon to be valid iff the LinearRing is valid.

However, for certain geometries (see first code section), the LinearRing might be valid, but the Polygon will turn out invalid. It looks like Polygon is more tolerant when detecting self-intersections, but that is not easily reproduced (see second code section).

An SVG of the geometry in question is attached.

### Actual reproduction with real-life geometry

    import re

    from shapely.geometry import Point, Polygon
    import shapely.validation
    import shapely.wkt

    wkt = 'LINEARRING Z (9.298500000000001 27.0718 12.2249, 9.297599999999999 27.0716 12.2237, 9.2958 27.0708 12.2214, 9.2773 27.0572 12.1725, 9.239800000000001 27.0388 12.092, 9.227499999999999 27.0293 12.0186, 9.2281 27.0241 11.9894, 9.2303 27.0248 11.988, 9.229200000000001 27.0247 11.9829, 9.2272 27.0385 11.8743, 9.2303 27.0422 11.8655, 9.231299999999999 27.0437 11.8603, 9.233599999999999 27.0461 11.8561, 9.232100000000001 27.0495 11.8459, 9.231 27.0743 11.7946, 9.233000000000001 27.0815 11.785, 9.233700000000001 27.085 11.78, 9.235099999999999 27.0889 11.7758, 9.234500000000001 27.0933 11.7715, 9.235200000000001 27.0985 11.7685, 9.298500000000001 27.0718 12.2249)'

    ring = shapely.wkt.loads(wkt)

    print(f"Ring is valid: {ring.is_valid}")

    polygon = Polygon(ring)

    explanation = shapely.validation.explain_validity(polygon)
    print(f"Polygon is valid: {polygon.is_valid}, explanation: {explanation}")

    intersection = Point(map(float, re.findall(r'[0-9.]+', explanation)))

    of = open('vr_ip.svg', 'w')
    of.write('<svg>\n')
    of.write(ring.svg())
    of.write(polygon.svg())
    of.write(intersection.svg())
    of.write('</svg>\n')
    of.close()

### Would-be generic reproduction (DOES NOT REPRODUCE THE PROBLEM!)

    from shapely.geometry import LinearRing, Polygon

    from shapely import validation

    for y in [1, 1e-12, 1e-25, 1e-50, 1e-120, 1e-250, 0]:
        p = [(0,2), (0,0), (2,0), (2,2), (1, y)]
        ring = LinearRing(p)
        polygon = Polygon(ring)
        print(f"==================== y = {y} ===============")
        print(f"Ring is valid: {ring.is_valid}")
        explanation = validation.explain_validity(polygon)
        print(f"Polygon is valid: {polygon.is_valid}, explanation: {explanation}")

## Operating system

Windows 10

## Shapely version and provenance

1.7.0, conda

## Edit
Simplified the repro script.

**Comment by jorisvandenbossche** [comment] 2021-12-27 14:43
@jpmaterial thanks for the report!

What version of GEOS is installed? 
It might be this is already fixed in a more recent version, as I can't reproduce the LinearRing being valid using the latest versions:

```
In [6]: import shapely

In [7]: shapely.__version__
Out[7]: '1.8.0'

In [8]: shapely.geos.geos_version
Out[8]: (3, 10, 1)

In [9]: import shapely.wkt

In [10]: wkt = 'LINEARRING Z (9.298500000000001 27.0718 12.2249, 9.297599999999999 27.0716 12.2237, 9.2958 27.0708 12.2214, 9.2773 27.0572 12.1725, 9.239800000000001 27.0388 12.092, 9.227499999999999 27.0293 12.0186, 9.2281 27.0241 11.9894, 9.2303 27.0248 11.988, 9.229200000000001 27.0247 11.9829, 9.2272 27.0385 11.8743, 9.2303 27.0422 11.8655, 9.231299999999999 27.0437 11.8603, 9.233599999999999 27.0461 11.8561, 9.232100000000001 27.0495 11.8459, 9.231 27.0743 11.7946, 9.233000000000001 27.0815 11.785, 9.233700000000001 27.085 11.78, 9.235099999999999 27.0889 11.7758, 9.234500000000001 27.0933 11.7715, 9.235200000000001 27.0985 11.7685, 9.298500000000001 27.0718 12.2249)'

In [11]: ring = shapely.wkt.loads(wkt)

In [12]: ring.is_valid
Out[12]: False
```

**Comment by jpmaterial** [comment] 2022-01-03 07:13
My GEOS version is 3.8.0.

I don't quite see why this is how the situation is resolved, as the ring does not self-intersect. (I'll attach an SVG to the issue.)

I can work with ring and polygon being valid or the status quo, but both being invalid is not helpful to me.

**Comment by jorisvandenbossche** [comment] 2022-01-03 08:20
@jpmaterial it seems you have removed your comment about the LinearRing actually being valid. Does that mean it's correctly labeled as invalid? 
Checking validity gives `'Ring Self-intersection[9.22842931016213 27.0300177598813 11.9825985906538]'`, and making a quick plot also seems to confirm that.

**Comment by jpmaterial** [comment] 2022-01-03 08:23
Yes. Looks like the GEOS fix is exactly what was needed.

**Comment by jorisvandenbossche** [comment] 2022-01-03 08:52
OK, thanks for the confirmation, closing this then

**Closed by jorisvandenbossche** 2022-01-03 08:52 UTC
Labels: geos
